### ISSUE TITLE
`sample` fixture fails if pytest is not called from specific folder

### ISSUE THREAD

**Issue by DropD** [greschd/aiida_pytest#6]
The `sample` fixture generates paths relative to the working directory from which `pytest` was called. This makes it inconvenient to use when one has tests in different locations as well.

**Comment by DropD** [comment]
Example for getting the directory from which a function is called:

```python
import inspect
from os.path import abspath, dirname

def caller_folder():
    frame = inspect.stack()[1]
    module = inspect.getmodule(frame[0])
    return dirname(abspath(module.__file__))
```

**Comment by greschd** [comment]
Note to self: See how this is fixed in the TBmodels test suite.

**Comment by greschd** [comment]
Note: I implemented the second option, because the ``conftest.py`` location isn't really a well-defined concept within ``pytest``.
